---
title: "Final Project"
author: "S&DS 230/S&DS 530/ENV 757/PLSC 530"
subtitle: Due by 11:59am, Saturday, May 7, 2022
output:
  html_document: default
  word_document: default
  pdf_document: default
---

**1)  Data Cleaning** - demonstrate use of find/replace, data cleaning, dealing with missing 
values, text character replacement, matching.  It is ok if your data did not require much of 
this.

**2)  Scraping More Info on S&P 500 Companies** - show appropriate use of at least ONE of each of the following – boxplot, 
scatterplot (can be matrix plot), normal quantile plot (can be related to regression), 
residual plots, histogram.

**3)  Basic Tests** - t-test, correlation, AND ability to create bootstrap confidence interval for 
either a t-test or a correlation.

**4)  Permutation Test** - include at least one.

**5)  Multiple Regression** - use either backwards stepwise regression or some form of best 
subsets regression.  Should include residual plots.  A GLM with a mix of continuous and 
categorical predictors is fine here.

**6)  AT LEAST ONE OF THE FOLLOWING TECHNIQUES** - ANOVA, ANCOVA, Logistic 
Regression, Multinomial Regression, OR data scraping off a website.


